COMMENT=		static files.

GH_PROJECT=		design
GH_ACCOUNT=		exordev
GH_TAGNAME=		0.22
REVISION=		0

CATEGORIES=		www
HOMEPAGE=		https://design.exor.dev
MAINTAINER=		Jose G Perez Taveras <josegpt27@gmail.com>

# ISC
PERMIT_PACKAGE=		Yes

NO_BUILD=		Yes
NO_TEST=		Yes

PREFIX=			${VARBASE}

.include <bsd.port.mk>
