COMMENT= 		design static files.

GH_PROJECT=		design
GH_ACCOUNT=		josegpt
GH_TAGNAME=		0.13
REVISION=		0

CATEGORIES=		www
HOMEPAGE =		https://design.redhex.dev
MAINTAINER =		Jose G Perez Taveras <josegpt27@gmail.com>

# ISC
PERMIT_PACKAGE =	Yes

NO_BUILD = 		Yes
NO_TEST =		Yes
PREFIX =		${VARBASE}/www

.include <bsd.port.mk>
