COMMENT= 		my personal website.

GH_PROJECT=		josegpt
GH_ACCOUNT=		josegpt
GH_TAGNAME=		0.24
REVISION=		0

CATEGORIES=		www
HOMEPAGE=		https://josegpt.com
MAINTAINER=		Jose G Perez Taveras <josegpt27@gmail.com>

# ISC
PERMIT_PACKAGE=		Yes

NO_TEST=		Yes
NO_BUILD=		Yes
PREFIX=			${VARBASE}/www

.include <bsd.port.mk>
