COMMENT=		static files.

GH_PROJECT=		josegpt
GH_ACCOUNT=		josegpt
GH_TAGNAME=		0.25
REVISION=		0

CATEGORIES=		www
HOMEPAGE=		https://josegpt.com
MAINTAINER=		Jose G Perez Taveras <josegpt27@gmail.com>

# ISC
PERMIT_PACKAGE=		Yes

NO_BUILD=		Yes
NO_TEST=		Yes

PREFIX=			${VARBASE}

.include <bsd.port.mk>
