COMMENT=		etc.

GH_PROJECT=		etc
GH_ACCOUNT=		exordev
GH_TAGNAME=		0.2
REVISION=		0

CATEGORIES=		www
HOMEPAGE=		https://github.com/exordev/etc
MAINTAINER=		Jose G Perez Taveras <josegpt27@gmail.com>

# ISC
PERMIT_PACKAGE=		Yes

NO_BUILD=		Yes
NO_TEST=		Yes

PREFIX=			${SYSCONFDIR}

.include <bsd.port.mk>
