COMMENT= 		immediate mode html generation library in c.

GH_PROJECT=		libhtml
GH_ACCOUNT=		exordev
GH_TAGNAME=		0.1
REVISION=		0

CATEGORIES=		devel
HOMEPAGE=		https://github.com/exordev/libhtml
MAINTAINER=		Jose G Perez Taveras <josegpt27@gmail.com>

# ISC
PERMIT_PACKAGE=		Yes

NO_TEST=		Yes

.include <bsd.port.mk>
