COMMENT= 		immediate mode html generation library in c.

GH_PROJECT=		libhtml
GH_ACCOUNT=		josegpt
GH_TAGNAME=		0.1
REVISION=		0

CATEGORIES=		devel
HOMEPAGE=		https://github.com/josegpt/libhtml
MAINTAINER=		Jose G Perez Taveras <josegpt27@gmail.com>

# ISC
PERMIT_PACKAGE=		Yes

# uses pledge()
NO_TEST=		Yes

.include <bsd.port.mk>
