COMMENT=		publicaddr.net.

GH_PROJECT=		publicaddr
GH_ACCOUNT=		exordev
GH_TAGNAME=		0.3
REVISION=		0

CATEGORIES=		www
HOMEPAGE=		https://publicaddr.net
MAINTAINER=		Jose G Perez Taveras <josegpt27@gmail.com>

# ISC
PERMIT_PACKAGE=		Yes

# uses pledge()
NO_TEST=		Yes

PREFIX=			${VARBASE}

.include <bsd.port.mk>
