COMMENT= 	relayd config.

GH_PROJECT=	relayd.conf
GH_ACCOUNT=	josegpt
GH_TAGNAME=	0.1
REVISION=	0

CATEGORIES=	www
HOMEPAGE=	https://redhex.dev
MAINTAINER=	Jose G Perez Taveras <josegpt27@gmail.com>

# ISC
PERMIT_PACKAGE=	Yes

NO_BUILD=	Yes
NO_TEST=	Yes

PREFIX=		${SYSCONFDIR}

.include <bsd.port.mk>
