COMMENT = 		static files for all my services.

V =			1.6.0
DISTNAME =		static-v${V}
PKGNAME =		static-${V}
REVISION =		0

CATEGORIES =		www

HOMEPAGE =		https://git.sr.ht/~josegpt/static

MAINTAINER =		Jose G Perez Taveras <josegpt27@gmail.com>

# GPL-3.0-or-later
PERMIT_PACKAGE =	Yes
MASTER_SITES =		https://git.sr.ht/~josegpt/
DISTFILES =		static-{static/archive/v}${V}${EXTRACT_SUFX}

PREFIX =		${VARBASE}/www

NO_BUILD = 		Yes
NO_TEST =		Yes

.include <bsd.port.mk>
