#!/sbin/openrc-run
name="josegpt.com"
description="My personal website service"
supervisor=supervise-daemon
JOSEGPT_USER=${JOSEGPT_USER:-josegpt.com}
JOSEGPT_PORT=${JOSEGPT_PORT:-3000}
JOSEGPT_ARGS=${JOSEGPT_ARGS:-}
LOGS=/var/log/josegpt.com.log
supervise_daemon_args="-1 $LOGS -2 $LOGS"
command="/usr/bin/$name"
command_args="-port $JOSEGPT_PORT $JOSEGPT_ARGS"
command_user="$JOSEGPT_USER:$JOSEGPT_USER"
pidfile="/run/${RC_SVCNAME}.pid"

depend() {
	need net
}

start_pre() {
  checkpath -f "$LOGS" -m 644 -o "$JOSEGPT_USER:$JOSEGPT_USER"
}