COMMENT = 		configuration for my alphabet.

V =			1.3.0
DISTNAME =		alphabet-v${V}
PKGNAME =		alphabet-${V}
REVISION =		1

CATEGORIES =		www

HOMEPAGE =		https://git.sr.ht/~josegpt/alphabet

MAINTAINER =		Jose G Perez Taveras <josegpt27@gmail.com>

# ISC
PERMIT_PACKAGE =	Yes
MASTER_SITES =		https://git.sr.ht/~josegpt/
DISTFILES =		alphabet-{alphabet/archive/v}${V}${EXTRACT_SUFX}

NO_BUILD =		Yes
NO_TEST =		Yes

PREFIX =		${SYSCONFDIR}

.include <bsd.port.mk>
