COMMENT =		mtaveras.com personal site.

V =			0.4.1
MODGO_MODNAME =		git.sr.ht/~josegpt/mtaveras.com
MODGO_VERSION =		v${V}
DISTNAME =		mtaveras.com-${V}
REVISION =		0

CATEGORIES =		www
HOMEPAGE =		https://mtaveras.com
MAINTAINER =		Jose G Perez Taveras <josegpt27@gmail.com>

# ISC
PERMIT_PACKAGE =	Yes

# uses pledge()
WANTLIB +=		c pthread

MODULES =		lang/go

.include <bsd.port.mk>
