COMMENT-main=		exor config files.
COMMENT-www= 		exor www files.

GH_PROJECT=		src
GH_ACCOUNT=		exordev
GH_TAGNAME=		0.2
REVISION=		0

CATEGORIES=		www
MULTI_PACKAGES=		-main -www
HOMEPAGE=		https://exor.dev
MAINTAINER=		Jose G Perez Taveras <josegpt27@gmail.com>

# ISC
PERMIT_PACKAGE=		Yes

# uses pledge()
NO_TEST=		Yes

PREFIX-main=		${SYSCONFDIR}
PREFIX-www=		${VARBASE}/www

.include <bsd.port.mk>
