COMMENT =			PTServer configuration

V =				0.0.1
DISTNAME =			ptserver-conf-${V}
REVISION =			0

CATEGORIES =		www

HOMEPAGE =			https://josegpt.com

MAINTAINER =		Jose G Perez Taveras <josegpt27@gmail.com>

# 0BSD
PERMIT_PACKAGE =	Yes

# MASTER_SITES =		???

NO_BUILD =			Yes
NO_TEST =			Yes

.include <bsd.port.mk>
